name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq libatk1.0-0 libc6 libcairo2 xdg-utils wget \
            libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 \
            libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
            libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
            libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test

      - name: Integration tests
        run: yarn e2e

      - name: Build
        run: yarn build

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: new-collections
          path: ./dist/new-collections
